language: objective-c

xcode_workspace: Gambattye.xcworkspace
xcode_scheme: Gambattye

osx_image: xcode10.2

install: travis_wait pod repo update --silent && pod install --repo-update && gem install xcpretty

script: set -o pipefail && xcodebuild -workspace Gambattye.xcworkspace -scheme Gambattye | xcpretty
