language: objective-c

xcode_workspace: Gambattye.xcworkspace
xcode_scheme: Gambattye

osx_image: xcode9

install: travis_wait pod repo update --silent && pod install

script: xcodebuild -workspace Gambattye.xcworkspace -scheme Gambattye
